// Hardcoded scenarios for Dijkstra pathfinding demo
// Each scenario uses a DIFFERENT area of London so the map pans when switching
const scenarios = [
  {
    id: 1,
    name: "Scenario 1: Westminster Rush Hour",
    description: "Moderate traffic across Westminster. A direct route is available but slightly congested.",
    center: [51.501, -0.125],
    zoom: 15,
    nodes: [
      { id: "A", name: "Ambulance Station Alpha", type: "Ambulance", lat: 51.501, lng: -0.125 },
      { id: "N1", name: "Parliament Square", type: "Intersection", lat: 51.500, lng: -0.127 },
      { id: "N2", name: "Victoria Embankment", type: "Intersection", lat: 51.504, lng: -0.120 },
      { id: "I1", name: "Whitehall Junction", type: "Intersection", lat: 51.503, lng: -0.126 },
      { id: "I2", name: "Trafalgar Link", type: "Intersection", lat: 51.507, lng: -0.128 },
      { id: "I3", name: "Bridge Street", type: "Intersection", lat: 51.499, lng: -0.122 },
      { id: "I4", name: "Millbank Road", type: "Intersection", lat: 51.496, lng: -0.126 },
      { id: "I5", name: "Strand Crossing", type: "Intersection", lat: 51.509, lng: -0.121 },
      { id: "I6", name: "Lambeth Approach", type: "Intersection", lat: 51.497, lng: -0.119 },
      { id: "P_ALPHA", name: "Patient Alpha", type: "Patient", lat: 51.508, lng: -0.131 },
      { id: "P_BETA", name: "Patient Beta", type: "Patient", lat: 51.496, lng: -0.117 },
      { id: "H1", name: "St Thomas' Hospital", type: "Hospital", lat: 51.498, lng: -0.116 },
      { id: "H2", name: "Westminster Medical", type: "Hospital", lat: 51.510, lng: -0.120 }
    ],
    edges: [
      { from: "A", to: "N1", weight: 3, traffic: "Normal" },
      { from: "A", to: "N2", weight: 4, traffic: "Normal" },
      { from: "A", to: "I1", weight: 2, traffic: "Normal" },
      { from: "A", to: "I3", weight: 3, traffic: "Normal" },
      { from: "N1", to: "I1", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I4", weight: 3, traffic: "Normal" },
      { from: "I1", to: "I2", weight: 3, traffic: "Heavy" },
      { from: "I1", to: "N2", weight: 3, traffic: "Normal" },
      { from: "I2", to: "P_ALPHA", weight: 2, traffic: "Normal" },
      { from: "I2", to: "I5", weight: 2, traffic: "Normal" },
      { from: "N2", to: "I5", weight: 3, traffic: "Heavy" },
      { from: "I3", to: "I6", weight: 3, traffic: "Normal" },
      { from: "I3", to: "I4", weight: 2, traffic: "Normal" },
      { from: "I4", to: "P_BETA", weight: 4, traffic: "Normal" },
      { from: "I6", to: "P_BETA", weight: 2, traffic: "Normal" },
      { from: "I6", to: "H1", weight: 2, traffic: "Normal" },
      { from: "P_BETA", to: "H1", weight: 2, traffic: "Normal" },
      { from: "P_ALPHA", to: "H2", weight: 3, traffic: "Normal" },
      { from: "I5", to: "H2", weight: 2, traffic: "Normal" },
      { from: "P_ALPHA", to: "I1", weight: 5, traffic: "Heavy" },
      { from: "I4", to: "H1", weight: 4, traffic: "Normal" },
      { from: "I5", to: "P_ALPHA", weight: 3, traffic: "Normal" },
      { from: "N2", to: "I3", weight: 4, traffic: "Normal" }
    ],
    patients: [
      { id: "P_ALPHA", name: "John Doe (Cardiac)", age: 64, severity: "CRITICAL", level: 1, startNode: "A", patientNode: "P_ALPHA", targetHospital: "H2", distance: "1.8 km" },
      { id: "P_BETA", name: "Jane Smith (Fracture)", age: 32, severity: "URGENT", level: 2, startNode: "A", patientNode: "P_BETA", targetHospital: "H1", distance: "1.2 km" }
    ]
  },
  {
    id: 2,
    name: "Scenario 2: Canary Wharf Gridlock",
    description: "A major accident has blocked the main highway. Routing must bypass through secondary streets.",
    center: [51.505, -0.020],
    zoom: 15,
    nodes: [
      { id: "A", name: "Docklands Ambulance Unit", type: "Ambulance", lat: 51.505, lng: -0.020 },
      { id: "N1", name: "Westferry Road", type: "Intersection", lat: 51.508, lng: -0.024 },
      { id: "N2", name: "Marsh Wall", type: "Intersection", lat: 51.502, lng: -0.018 },
      { id: "I1", name: "Canada Square", type: "Intersection", lat: 51.505, lng: -0.017 },
      { id: "I2", name: "Jubilee Line Exit", type: "Intersection", lat: 51.509, lng: -0.019 },
      { id: "I3", name: "Heron Quay", type: "Intersection", lat: 51.503, lng: -0.022 },
      { id: "I4", name: "South Dock Bridge", type: "Intersection", lat: 51.500, lng: -0.021 },
      { id: "I5", name: "Poplar Link", type: "Intersection", lat: 51.511, lng: -0.016 },
      { id: "I6", name: "Limehouse Cut", type: "Intersection", lat: 51.500, lng: -0.014 },
      { id: "P_ALPHA", name: "Patient Alpha", type: "Patient", lat: 51.510, lng: -0.025 },
      { id: "P_BETA", name: "Patient Beta", type: "Patient", lat: 51.499, lng: -0.013 },
      { id: "H1", name: "Royal London Hospital", type: "Hospital", lat: 51.512, lng: -0.014 },
      { id: "H2", name: "Docklands Clinic", type: "Hospital", lat: 51.497, lng: -0.022 }
    ],
    edges: [
      { from: "A", to: "N1", weight: 25, traffic: "Gridlock" },
      { from: "A", to: "N2", weight: 3, traffic: "Normal" },
      { from: "A", to: "I1", weight: 2, traffic: "Normal" },
      { from: "A", to: "I3", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I2", weight: 12, traffic: "Heavy" },
      { from: "N1", to: "P_ALPHA", weight: 20, traffic: "Gridlock" },
      { from: "I1", to: "I2", weight: 3, traffic: "Normal" },
      { from: "I2", to: "P_ALPHA", weight: 3, traffic: "Normal" },
      { from: "I2", to: "I5", weight: 2, traffic: "Normal" },
      { from: "I3", to: "I4", weight: 2, traffic: "Normal" },
      { from: "I3", to: "N2", weight: 2, traffic: "Normal" },
      { from: "I4", to: "H2", weight: 2, traffic: "Normal" },
      { from: "N2", to: "I6", weight: 3, traffic: "Normal" },
      { from: "I6", to: "P_BETA", weight: 2, traffic: "Normal" },
      { from: "I5", to: "H1", weight: 2, traffic: "Normal" },
      { from: "I5", to: "P_ALPHA", weight: 4, traffic: "Normal" },
      { from: "P_ALPHA", to: "H1", weight: 5, traffic: "Normal" },
      { from: "P_ALPHA", to: "H2", weight: 9, traffic: "Heavy" },
      { from: "P_BETA", to: "H1", weight: 7, traffic: "Normal" },
      { from: "P_BETA", to: "H2", weight: 6, traffic: "Normal" },
      { from: "P_BETA", to: "I6", weight: 2, traffic: "Normal" },
      { from: "I4", to: "P_BETA", weight: 5, traffic: "Normal" },
      { from: "I1", to: "I5", weight: 4, traffic: "Heavy" },
      { from: "N2", to: "H2", weight: 3, traffic: "Normal" },
      { from: "I6", to: "H2", weight: 4, traffic: "Normal" }
    ],
    patients: [
      { id: "P_ALPHA", name: "Ahmed Khan (Head Trauma)", age: 45, severity: "CRITICAL", level: 1, startNode: "A", patientNode: "P_ALPHA", targetHospital: "H1", distance: "2.1 km" },
      { id: "P_BETA", name: "Lisa Park (Burn Injury)", age: 29, severity: "URGENT", level: 2, startNode: "A", patientNode: "P_BETA", targetHospital: "H2", distance: "1.5 km" }
    ]
  },
  {
    id: 3,
    name: "Scenario 3: King's Cross Flooding",
    description: "Heavy rain has flooded southern approaches near King's Cross. Northern bypass routes required.",
    center: [51.532, -0.123],
    zoom: 15,
    nodes: [
      { id: "A", name: "King's Cross Station Unit", type: "Ambulance", lat: 51.532, lng: -0.123 },
      { id: "N1", name: "Euston Road", type: "Intersection", lat: 51.529, lng: -0.127 },
      { id: "N2", name: "Pentonville Road", type: "Intersection", lat: 51.531, lng: -0.116 },
      { id: "I1", name: "Caledonian Road", type: "Intersection", lat: 51.535, lng: -0.120 },
      { id: "I2", name: "York Way", type: "Intersection", lat: 51.537, lng: -0.125 },
      { id: "I3", name: "Gray's Inn Road", type: "Intersection", lat: 51.528, lng: -0.121 },
      { id: "I4", name: "Bloomsbury Link", type: "Intersection", lat: 51.526, lng: -0.125 },
      { id: "I5", name: "Angel Junction", type: "Intersection", lat: 51.534, lng: -0.114 },
      { id: "I6", name: "Russell Square", type: "Intersection", lat: 51.524, lng: -0.119 },
      { id: "P_GAMMA", name: "Patient Gamma", type: "Patient", lat: 51.536, lng: -0.128 },
      { id: "P_DELTA", name: "Patient Delta", type: "Patient", lat: 51.533, lng: -0.112 },
      { id: "H1", name: "University College Hospital", type: "Hospital", lat: 51.525, lng: -0.129 },
      { id: "H2", name: "Moorfields Eye Hospital", type: "Hospital", lat: 51.527, lng: -0.113 }
    ],
    edges: [
      { from: "A", to: "N1", weight: 3, traffic: "Normal" },
      { from: "A", to: "N2", weight: 4, traffic: "Normal" },
      { from: "A", to: "I1", weight: 2, traffic: "Normal" },
      { from: "A", to: "I3", weight: 30, traffic: "Gridlock" },
      { from: "N1", to: "I4", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I3", weight: 25, traffic: "Gridlock" },
      { from: "I1", to: "I2", weight: 2, traffic: "Normal" },
      { from: "I2", to: "P_GAMMA", weight: 2, traffic: "Normal" },
      { from: "I1", to: "I5", weight: 3, traffic: "Normal" },
      { from: "N2", to: "I5", weight: 3, traffic: "Normal" },
      { from: "I5", to: "P_DELTA", weight: 2, traffic: "Normal" },
      { from: "I3", to: "I6", weight: 20, traffic: "Gridlock" },
      { from: "I4", to: "H1", weight: 2, traffic: "Normal" },
      { from: "I4", to: "I6", weight: 2, traffic: "Normal" },
      { from: "I6", to: "H2", weight: 3, traffic: "Normal" },
      { from: "P_GAMMA", to: "H1", weight: 5, traffic: "Normal" },
      { from: "P_GAMMA", to: "I2", weight: 2, traffic: "Normal" },
      { from: "P_GAMMA", to: "I1", weight: 3, traffic: "Normal" },
      { from: "P_DELTA", to: "H2", weight: 3, traffic: "Normal" },
      { from: "P_DELTA", to: "I5", weight: 2, traffic: "Normal" },
      { from: "N2", to: "I3", weight: 22, traffic: "Gridlock" },
      { from: "I6", to: "H1", weight: 4, traffic: "Normal" },
      { from: "N1", to: "H1", weight: 3, traffic: "Normal" },
      { from: "N2", to: "H2", weight: 4, traffic: "Normal" }
    ],
    patients: [
      { id: "P_GAMMA", name: "Marcus Reed (Stroke)", age: 71, severity: "CRITICAL", level: 1, startNode: "A", patientNode: "P_GAMMA", targetHospital: "H1", distance: "1.6 km" },
      { id: "P_DELTA", name: "Alice Cooper (Allergy)", age: 25, severity: "URGENT", level: 2, startNode: "A", patientNode: "P_DELTA", targetHospital: "H2", distance: "1.3 km" }
    ]
  },
  {
    id: 4,
    name: "Scenario 4: Brixton Concert Event",
    description: "Massive concert near Brixton Academy. Roads are heavily congested around the venue.",
    center: [51.462, -0.115],
    zoom: 15,
    nodes: [
      { id: "A", name: "Brixton Station Unit", type: "Ambulance", lat: 51.462, lng: -0.115 },
      { id: "N1", name: "Brixton Road", type: "Intersection", lat: 51.465, lng: -0.118 },
      { id: "N2", name: "Coldharbour Lane", type: "Intersection", lat: 51.460, lng: -0.110 },
      { id: "I1", name: "Acre Lane", type: "Intersection", lat: 51.464, lng: -0.112 },
      { id: "I2", name: "Stockwell Link", type: "Intersection", lat: 51.468, lng: -0.117 },
      { id: "I3", name: "Loughborough Junction", type: "Intersection", lat: 51.460, lng: -0.113 },
      { id: "I4", name: "Vassall Road", type: "Intersection", lat: 51.458, lng: -0.117 },
      { id: "I5", name: "Camberwell Approach", type: "Intersection", lat: 51.466, lng: -0.108 },
      { id: "I6", name: "Herne Hill Road", type: "Intersection", lat: 51.457, lng: -0.110 },
      { id: "P_EPSILON", name: "Patient Epsilon", type: "Patient", lat: 51.467, lng: -0.120 },
      { id: "H1", name: "King's College Hospital", type: "Hospital", lat: 51.469, lng: -0.106 },
      { id: "H2", name: "Brixton Community Clinic", type: "Hospital", lat: 51.456, lng: -0.118 }
    ],
    edges: [
      { from: "A", to: "N1", weight: 3, traffic: "Normal" },
      { from: "A", to: "N2", weight: 3, traffic: "Normal" },
      { from: "A", to: "I1", weight: 2, traffic: "Normal" },
      { from: "A", to: "I3", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I2", weight: 2, traffic: "Normal" },
      { from: "N1", to: "P_EPSILON", weight: 4, traffic: "Normal" },
      { from: "I2", to: "P_EPSILON", weight: 18, traffic: "Gridlock" },
      { from: "I1", to: "I2", weight: 3, traffic: "Normal" },
      { from: "I1", to: "I5", weight: 3, traffic: "Normal" },
      { from: "I1", to: "N1", weight: 2, traffic: "Normal" },
      { from: "I3", to: "I4", weight: 2, traffic: "Normal" },
      { from: "I3", to: "N2", weight: 2, traffic: "Normal" },
      { from: "I4", to: "H2", weight: 2, traffic: "Normal" },
      { from: "I6", to: "H2", weight: 3, traffic: "Normal" },
      { from: "N2", to: "I6", weight: 3, traffic: "Normal" },
      { from: "I5", to: "H1", weight: 2, traffic: "Normal" },
      { from: "I2", to: "I5", weight: 4, traffic: "Heavy" },
      { from: "P_EPSILON", to: "H1", weight: 22, traffic: "Gridlock" },
      { from: "P_EPSILON", to: "H2", weight: 6, traffic: "Normal" },
      { from: "P_EPSILON", to: "I2", weight: 18, traffic: "Gridlock" },
      { from: "I4", to: "I6", weight: 3, traffic: "Normal" },
      { from: "N2", to: "H1", weight: 5, traffic: "Normal" }
    ],
    patients: [
      { id: "P_EPSILON", name: "Bob Marley (Asthma)", age: 45, severity: "CRITICAL", level: 1, startNode: "A", patientNode: "P_EPSILON", targetHospital: "H2", distance: "1.4 km" }
    ]
  },
  {
    id: 5,
    name: "Scenario 5: Chelsea Midnight Run",
    description: "Zero traffic overnight. Pure distance-based routing across Chelsea and South Kensington.",
    center: [51.490, -0.175],
    zoom: 15,
    nodes: [
      { id: "A", name: "Chelsea Station Unit", type: "Ambulance", lat: 51.490, lng: -0.175 },
      { id: "N1", name: "King's Road", type: "Intersection", lat: 51.488, lng: -0.170 },
      { id: "N2", name: "Fulham Road", type: "Intersection", lat: 51.486, lng: -0.177 },
      { id: "I1", name: "Sloane Square", type: "Intersection", lat: 51.492, lng: -0.172 },
      { id: "I2", name: "Brompton Cross", type: "Intersection", lat: 51.494, lng: -0.176 },
      { id: "I3", name: "Beaufort Street", type: "Intersection", lat: 51.487, lng: -0.173 },
      { id: "I4", name: "World's End", type: "Intersection", lat: 51.484, lng: -0.178 },
      { id: "I5", name: "South Kensington", type: "Intersection", lat: 51.494, lng: -0.170 },
      { id: "I6", name: "Battersea Bridge", type: "Intersection", lat: 51.484, lng: -0.172 },
      { id: "P_ZETA", name: "Patient Zeta", type: "Patient", lat: 51.493, lng: -0.178 },
      { id: "H1", name: "Chelsea & Westminster Hospital", type: "Hospital", lat: 51.485, lng: -0.182 },
      { id: "H2", name: "Royal Marsden Hospital", type: "Hospital", lat: 51.496, lng: -0.168 }
    ],
    edges: [
      { from: "A", to: "N1", weight: 2, traffic: "Normal" },
      { from: "A", to: "N2", weight: 2, traffic: "Normal" },
      { from: "A", to: "I1", weight: 2, traffic: "Normal" },
      { from: "A", to: "I3", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I1", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I3", weight: 2, traffic: "Normal" },
      { from: "I1", to: "I2", weight: 2, traffic: "Normal" },
      { from: "I1", to: "I5", weight: 2, traffic: "Normal" },
      { from: "I2", to: "P_ZETA", weight: 2, traffic: "Normal" },
      { from: "I2", to: "I5", weight: 2, traffic: "Normal" },
      { from: "I3", to: "I4", weight: 2, traffic: "Normal" },
      { from: "I3", to: "I6", weight: 2, traffic: "Normal" },
      { from: "I4", to: "N2", weight: 2, traffic: "Normal" },
      { from: "I4", to: "H1", weight: 2, traffic: "Normal" },
      { from: "N2", to: "H1", weight: 2, traffic: "Normal" },
      { from: "I5", to: "H2", weight: 2, traffic: "Normal" },
      { from: "I6", to: "H1", weight: 3, traffic: "Normal" },
      { from: "I6", to: "I4", weight: 2, traffic: "Normal" },
      { from: "P_ZETA", to: "H1", weight: 4, traffic: "Normal" },
      { from: "P_ZETA", to: "H2", weight: 3, traffic: "Normal" },
      { from: "P_ZETA", to: "I2", weight: 2, traffic: "Normal" },
      { from: "N2", to: "I3", weight: 2, traffic: "Normal" },
      { from: "N1", to: "I6", weight: 3, traffic: "Normal" }
    ],
    patients: [
      { id: "P_ZETA", name: "Zara Hughes (Laceration)", age: 50, severity: "URGENT", level: 2, startNode: "A", patientNode: "P_ZETA", targetHospital: "H2", distance: "0.9 km" }
    ]
  }
];

module.exports = { scenarios };
